/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package openaudio;

import openaudio.models.Song;
import openaudio.controllers.MusicPlayerController;
import openaudio.controllers.CollectionController;
import openaudio.utils.Settings;
import openaudio.views.FocusView;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;


public class App extends Application {

    private MusicPlayerController musicPlayer;
    private FocusView focusView;

    @Override
    public void start(Stage stage) {
        Settings.getInstance().readProperties();

        this.musicPlayer = MusicPlayerController.getInstance();
        this.musicPlayer.initialize();

        CollectionController.getInstance().initialize(stage);

        this.focusView = FocusView.getInstance();
        
        BorderPane borderPane = new BorderPane();
        borderPane.setLeft(CollectionController.getInstance().getAlbumShelf());
        borderPane.setRight(CollectionController.getInstance().getPlaylistShelf());
        borderPane.setBottom(this.musicPlayer.getVBox());
        borderPane.setCenter(this.focusView.getVBox());
        Scene scene = new Scene(borderPane, 640, 480);
        scene.getStylesheets().add(getClass().getResource("/css/styles.css").toExternalForm());
        stage.setScene(scene);
        stage.show();
    }


    public static void main(String[] args) {
        launch();
    }

}