/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package openaudio;

import openaudio.models.Song;
import openaudio.controllers.MusicPlayerController;
import openaudio.controllers.AlbumController;
import openaudio.utils.Settings;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;


public class App extends Application {

    private MusicPlayerController musicPlayer;
    private AlbumController albumController;

    @Override
    public void start(Stage stage) {
        Settings.getInstance().readProperties();

        this.musicPlayer = new MusicPlayerController();
        this.musicPlayer.initialize();

        this.albumController = new AlbumController();
        this.albumController.initialize(stage);

        Song paranoidAndroid = new Song("Paranoid Android", "Radiohead", "OKNOTOK", 100.0f, "/home/user/Music/OK Computer/01 Airbag.mp3");
        this.musicPlayer.playSong(paranoidAndroid);
        BorderPane borderPane = new BorderPane();
        borderPane.setLeft(this.albumController.getVBox());
        borderPane.setBottom(this.musicPlayer.getVBox());
        Scene scene = new Scene(borderPane, 640, 480);
        stage.setScene(scene);
        stage.show();
    }


    public static void main(String[] args) {
        launch();
    }

}